nginx84:
  compose: deployment/services/nginx84/docker-compose.yml
  env: deployment/services/nginx84/.env.dist
  depends:
    - mysql

mysql:
  compose: deployment/services/mysql/docker-compose.yml
  env: deployment/services/mysql/.env.dist

