services:
  nginx:
    build:
      context: ./deployment/services/nginx84/build
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "${HTTP_PORT:-8000}:80"
      - "${HTTPS_PORT:-8443}:443"
    volumes:
          - .:/var/www/html
          - ./deployment/services/nginx84/conf/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./deployment/services/nginx84/conf/ssl.conf:/etc/nginx/conf.d/ssl.conf
          - ./deployment/services/nginx84/conf/xdebug.ini:/etc/php84/conf.d/50_xdebug.ini:ro
          - ./deployment/services/nginx84/ssl:/etc/nginx/ssl:ro
    working_dir: /var/www/html

    healthcheck:
      test: ["CMD-SHELL", "curl -f -k https://localhost:443/ || curl -f http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    networks:
      - default

networks:
    default:
        driver: bridge