services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - '${MYSQL_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD:-root}'
      MYSQL_DATABASE: '${MYSQL_DATABASE:-app}'
      MYSQL_USER: '${MYSQL_USER:-user}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD:-password}'
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
      - ./deployment/services/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - default
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
    driver: local
  mysql_config:
    driver: local

networks:
  default:
    driver: bridge
