services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - '${RABBITMQ_PORT:-5672}:5672'
      - '${RABBITMQ_MANAGEMENT_PORT:-15672}:15672'
    environment:
      RABBITMQ_DEFAULT_USER: '${RABBITMQ_USER:-guest}'
      RABBITMQ_DEFAULT_PASS: '${RABBITMQ_PASSWORD:-guest}'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - default
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  rabbitmq_data:
    driver: local

networks:
  default:
    driver: bridge
